services:
  accountsdb:
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
      container_name: loansdb
      ports:
        - 3307:3306
      environment:
        MYSQL_DATABASE: loansdb
      extends:
        file: common-config.yml
        service: microservice-db-config

  cardsdb:
      container_name: cardsdb
      ports:
        - 3308:3306
      environment:
        MYSQL_DATABASE: cardsdb
      extends:
        file: common-config.yml
        service: microservice-db-config

  configserver:
    image: "peterarokiasamy/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    #deploy:
      #resources:
        #limits:
          #memory: 700m
    #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "peterarokiasamy/accounts:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
    #deploy:
      #resources:
        #limits:
          #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
    #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "peterarokiasamy/loans:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
    #deploy:
      #resources:
        #limits:
          #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb" #Use 3306 port inside container
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
    # networks:
      # - peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "peterarokiasamy/cards:s7"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
    #deploy:
      #resources:
        #limits:
          #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb" #Use 3306 port inside container
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
    #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  peterarokiasamy:
    driver: "bridge"