spring:
  application:
    name: "configserver"
  profiles:
    #active: native #This tell the spring cloud config server that we can to active native profile of SCC server
    active: git #for Git Repo
  cloud:
    config:
      server:
        #Comment for Git Hub Config
        #native:
          #search-locations: "classpath:/config" #for classpath
          #search-locations: "file:///C://Users//User//Projects//arokia//config"
        git:
          uri: "https://github.com/peterarokiasamy/peter-arokia-config"
          default-label: main #default branch
          timeout: 5
          clone-on-start: true #Clone during startup and not when very first request to config server
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9" #Input Complex Key

server:
  port: 8071
