server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: '' #Empty Password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update #Dont Create table instead load from data.sql
    show-sql: true

  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
       - "qa"

build:
  version: "3.0"

accounts:
  message: "Welcome to Arokia accounts related local APIs "
  contactDetails:
    name: "John Alex - Developer"
    email: "john@arokia.com"
  onCallSupport:
    - (60) 1021-69-024
    - (44) 7440-38-281
