spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Arokia loans related QA APIs "
  contactDetails:
    name: "Prayan Arokia - QA Lead"
    email: "prayan@arokia.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371