services:
  network-deploy-service: #network related configuration
    networks:
      - peterarokiasamy

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root

  microservice-base-config:
    #Whenever new microservices created inside our docker-compose, it will extend this service
    #will be imported by other microsevice
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    #Will be used by MS which depends on config server.
    extends:
      service: microservice-base-config
    #In recent version of docker compose, its no longer possible to utilize both extends and depends on.
    #So depends_on still maintained inside docker compose rather than common-config yml
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      #DB Credentials
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root