services:
  configserver:
    image: "peterarokiasamy/configserver:s9"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
        #deploy:
        #resources:
        #limits:
      #memory: 700m
      #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "peterarokiasamy/eurekaserver:s9"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accounts:
    image: "peterarokiasamy/accounts:s9"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
        #deploy:
        #resources:
        #limits:
      #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: accounts
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
      #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "peterarokiasamy/loans:s9"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
        #deploy:
        #resources:
        #limits:
      #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: loans
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
      # networks:
      # - peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "peterarokiasamy/cards:s9"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
        #deploy:
        #resources:
        #limits:
      #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: cards
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
      #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "peterarokiasamy/gatewayserver:s9"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  peterarokiasamy:
    driver: "bridge"