services:
  kafka:
    image: docker.io/bitnami/kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    extends:
      file: common-config.yml
      service: network-deploy-service

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "peterarokiasamy/configserver:s14"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 20s
      retries: 30
      start_period: 30s
        #deploy:
        #resources:
        #limits:
      #memory: 700m
      #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-base-config
    environment:
      OTEL_SERVICE_NAME: "configserver"

  eurekaserver:
    image: "peterarokiasamy/eurekaserver:s14"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      OTEL_SERVICE_NAME: "eurekaserver"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 20s
      retries: 30
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accounts:
    image: "peterarokiasamy/accounts:s14"
    container_name: accounts-ms
    depends_on:
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
      kafka:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 20s
      retries: 30
      start_period: 30s
        #deploy:
        #resources:
        #limits:
      #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: accounts
      OTEL_SERVICE_NAME: "accounts"
      #SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
      #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "peterarokiasamy/loans:s14"
    container_name: loans-ms
    depends_on:
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 20s
      retries: 30
      start_period: 30s
        #deploy:
        #resources:
        #limits:
      #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: loans
      OTEL_SERVICE_NAME: "loans"
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
      # networks:
      # - peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "peterarokiasamy/cards:s14"
    container_name: cards-ms
    depends_on:
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 20s
      retries: 30
      start_period: 30s
        #deploy:
        #resources:
        #limits:
      #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: cards
      OTEL_SERVICE_NAME: "cards"
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
      #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  message:
    image: "peterarokiasamy/message:s14"
    container_name: message-ms
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
      #SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: network-deploy-service

  gatewayserver:
    image: "peterarokiasamy/gatewayserver:s14"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      OTEL_SERVICE_NAME: "gatewayserver"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

volumes:
  kafka_data:
    driver: local

networks:
  peterarokiasamy:
    driver: "bridge"