services:
  accounts:
    image: "peterarokiasamy/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - peterarokiasamy
  loans:
    image: "peterarokiasamy/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - peterarokiasamy
  cards:
    image: "peterarokiasamy/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - peterarokiasamy
networks:
  peterarokiasamy:
    driver: "bridge"