server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms #with help of | symbol, we are also combining both email and sms function

    stream:
      bindings:
        emailsms-in-0: #cloud.function.definition-input-0th index
          destination: send-communication #queue created in rabbitMQ to connect and monitor then send to above function
          group: ${spring.application.name} #without this rabbitMQ will append randomly generated value to destination
        emailsms-out-0:
          destination: communication-sent
      kafka:
        binder:
          brokers:
            - localhost:9092

