services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "peterarokiasamy/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
        #deploy:
        #resources:
        #limits:
      #memory: 700m
      #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "peterarokiasamy/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
          #deploy:
          #resources:
          #limits:
        #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: accounts
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
      #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "peterarokiasamy/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
          #deploy:
          #resources:
          #limits:
        #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: loans
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
      # networks:
      # - peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "peterarokiasamy/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver: # available configserver
        condition: service_healthy #other values service_started, service_completed_successfully
          #deploy:
          #resources:
          #limits:
        #memory: 700m
    environment:
      SPRING_APPLICATION_NAME: cards
      #SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #SPRING_PROFILE_ACTIVE: default
      #networks:
      #- peterarokiasamy Instead of this add below
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  peterarokiasamy:
    driver: "bridge"